### PR TITLE
Feature/uv and pypa structure

### PR DESCRIPTION
**Pull request by johacks**
Hi I started working on the other feature I mentioned but I found some issues/improvements that may be convenient to deal with:

- Project structure
    - Project is not structured according to python packaging standards. This almost always leads to headaches with the PYTHONPATH. I recommend structuring the project like: root/src/ai_dashboard_builder
- By adding a pyproject.toml it is easier to manage the package:
    - Set linting/formatter rules for a tool such as Ruff, so that it is easier to maintain consistent PEP8 rules among contributors.
    - Define development only dependencies in a more compact way.
    - Add an entrypoint script. I added one which allows doing something like `$ ai_dashboard_builder` from the shell to launch the server. This allows later on uploading your project to PyPi and users being able pip install it and then running that command to launch the application, which can be convenient.
    - Install dependencies with `uv` install of pip, which is a lightning fast environment manager that is really worth it.

With above changes I was able to easily update PEP8 inconsistencies in the code and create a development/production environment. I have created a [gist](https://gist.github.com/johacks/4ef917abf1b67066fc9890adab8f8801) with a recommended VS Code setup that integrates very well with this kind of ecosystem.

Let me know if any of these changes sounds good to you.

### CODE REVIEW

**Comment by pnmartinez** [comment]
Hi again @johacks ! 

Really interesting redactor. Will review today it tomorrow.

PS: this will be the first time I actually take a look at `uv`. Hope it lives up to the hype!

**Comment by pnmartinez** [comment]
Hi @johacks ,

I have briefly reviewed your refactor, and I am afraid I think I am encountering some issues:
- now the `docker-compose` auto creates an `.env` folder, which prevents using that name for the `.env` file storing the keys,
- this hurts importing the keys from the env file, but also it seems that now providing the API KEY through the web UI does not work anymore (I am always getting the error here: https://github.com/johacks/ai-dashboard-builder/blob/a3306d435f8130ec8e514a798c4d6e6d72e9dcfb/src/ai_dashboard_builder/llm/llm_pipeline.py#L111).

I will review more throgoughly, but not merging for now.

**Comment by johacks** [comment]
Hi @pnmartinez,

I just checked that in main branch both problems you mentioned are also present:
- `.env` folder is created because in both docker-compose.yml files you have volume: `- ./.env:/app/.env`, which will create a directory called `.env` if no file `.env` is in the host.
- I haven't checked source of the issue, but it seems in `main` branch i cannot provide API KEY through the web UI either, at least when i had no previously created `.env` file.

I suggest using instead docker compose directives for `.env` files: https://docs.docker.com/compose/how-tos/environment-variables/set-environment-variables/#use-the-env_file-attribute. Then I suggest avoiding reading a `.env` file in the python script altogether, as this will already be done by the docker compose process.

**Comment by pnmartinez** [comment]
Hi again @johacks ,

I can't reproduce these bugs on the main branch. What steps are you using to deploy? Are you using `docker compose up --build`?

See screenshots below:

- your fork creating the `.env` folder (and not being able to use the API token)
image

- a fresh instance of the `main`, just built, not creating any `.env` folder (and parsing and using the API TOKEN properly)
image

Please tell me how you are starting/deploying the app. I want to understand better the issues before proceeding.

**Comment by pnmartinez** [comment]
You're absolutely right @johacks . I guess I always place a copy of my `.env` there first.

I will be able to do an extensive review next Tuesday.

As a matter of fact: do you know any benchmark framework that we could deploy as a GitHub action?

**Review by pnmartinez — APPROVED** [review]
Hello @johacks !

I've finally able to test your PR thoroughly, as well as running some benchmarks.

I passed the logs of the build to Claude-3.5-sonnet to analyze them for me, getting:
```
Recommendation
Based on the KPIs, the UV approach appears superior:
- 43% faster overall build time
- 70% faster dependency installation
- Better dependency management
- Modern Python packaging practices
The main trade-off is slightly increased complexity, but the performance benefits and modern practices make this a worthwhile change. The UV approach would be especially beneficial in CI/CD pipelines where build time is crucial.```

I really appreciate your patience and effort, and let me invite you to keep colaborating.

Main areas to improve:
- fixing the storage of the `viz_specs.json` to reuse dashboards, as it is bad right now,
- design benchmarks to test different prompts in a quantitative manner.
- iterate and test different prompts.

Merging!

**Comment by johacks** [comment]
Hi @pnmartinez,

Glad to see the improvements, I think it is very cool that you analyzed the build logs with Claude 3.5.

Right now I have a little less time to work on new features, but I will let you know with an issue if I pick up anything from the roadmap later on.

Thanks!

**Pull request merged**
